[project]
name = "esm"
version = "3.2.1"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
channels = ["conda-forge", "bioconda", "ebetica0"]
description = "EvolutionaryScale open model repository"

[dependencies]
# faiss blocks 3.123
python = ">=3.12.11,<3.13"

[pypi-dependencies]
pre-commit = "*"
pytest = ">=8.3.3,<8.4"  # temp upper pin to deal with asyncio plugins not working with 8.4
pytest-asyncio = "*"
pytest-xdist = "*"
pytest-cov = "*"
pytest-timeout = "*"
ruff = "==0.7.3"
pyright = "==1.1.399" # Remember to change this in the pre-commit
pydantic = "*"
pydantic-settings = "*"

# editable install of curdir - makes esm package importable from anywhere
esm = { path = '.', editable = true }
