name: ESM Tests

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-precommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Environment
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.47.0
        cache: false
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    - name: Check formatting and typing
      run: |
          set -e
          # pyright seems to do something weird at initialization that causes it to error out
          # We can ignore the first invocation here.
          pyright esm/__init__.py || true
          pre-commit install
          env NODE_OPTIONS="--max-old-space-size=16384" pre-commit run --all-files --show-diff-on-failure
          [ -z "$(git status --porcelain)" ] && true || (echo "❌❌❌ pre-commit hook failed! A few files changed ❌❌❌]" && git status --porcelain && false)
          git reset --hard HEAD # test without the pre-commit changes
      shell: pixi run bash {0}
